
// General
export { default as GoldLine } from './gold line.png';
export { default as ScoreBoardHeader } from './ScoreBoard.png';
export { default as whiteBackground } from './bgSpecWhite.png';
export { default as blackBackground } from './bgSpecBlack.png';
export { default as RaidLeagueLogo } from './Logo.png';
export { default as LeftBans } from './left bans.png';
export { default as Bosses } from './boss container.png';
export { default as RightBans } from './right bans.png';
export { default as FilledGoldBar } from './FilledGoldBorder.png';
export { default as GoldBar } from './GoldBorder.png';

// Spec List Picks
export { default as Warrior } from './warrior.png';
export { default as Ele } from './elem.png';
export { default as Mesmer } from './mesmer.png';
export { default as Thief } from './thief.png';
export { default as Guardian } from './guardian.png';
export { default as Ranger } from './ranger.png';
export { default as Necro } from './necro.png';
export { default as Rev } from './revenant.png';
export { default as Engi } from './engi.png';
export { default as Berserker } from './berserker.png';
export { default as Tempest } from './tempest.png';
export { default as Chrono } from './chrono.png';
export { default as DareDevil } from './daredevil.png';
export { default as DH } from './dragonhunter.png';
export { default as Druid } from './druid.png';
export { default as Reaper } from './reaper.png';
export { default as Herald } from './herald.png';
export { default as Holo } from './Holo.png';
export { default as SpellBreaker } from './spellbreaker.png';
export { default as Weaver } from './weaver.png';
export { default as Mirage } from './mirage.png';
export { default as Deadeye } from './deadeye.png';
export { default as FB } from './firebrand.png';
export { default as SLB } from './soulbeast.png';
export { default as Scourge } from './scourge.png';
export { default as Renegade } from './renegade.png';
export { default as Scrapper } from './Scrapper.png';
export { default as Bladesworn } from './Bladesworn.png';
export { default as Catalyst } from './catalyst.png';
export { default as Virtuoso } from './virtuose.png';
export { default as Specter } from './specter.png';
export { default as WillBender } from './willbender.png';
export { default as Untamed } from './untamed.png';
export { default as Harbinger } from './harbinger.png';
export { default as Vindi } from './vindicator.png';
export { default as Mech } from './Mecha.png';

// Spec Logo List Squad Comp
export { default as WarriorLogo } from './specLogo/Warrior.png';
export { default as EleLogo } from './specLogo/Ele.png';
export { default as MesmerLogo } from './specLogo/Mesmer.png';
export { default as ThiefLogo } from './specLogo/Thief.png';
export { default as GuardianLogo } from './specLogo/Guardian.png';
export { default as RangerLogo } from './specLogo/Ranger.png';
export { default as NecroLogo } from './specLogo/Necro.png';
export { default as RevLogo } from './specLogo/Rev.png';
export { default as EngiLogo } from './specLogo/Engi.png';
export { default as BerserkerLogo } from './specLogo/Berserker.png';
export { default as TempestLogo } from './specLogo/Tempest.png';
export { default as ChronoLogo } from './specLogo/Chronomancer.png';
export { default as DareDevilLogo } from './specLogo/Daredevil.png';
export { default as DHLogo } from './specLogo/DragonHunter.png';
export { default as DruidLogo } from './specLogo/Druid.png';
export { default as ReaperLogo } from './specLogo/Reaper.png';
export { default as HeraldLogo } from './specLogo/Herald.png';
export { default as HoloLogo } from './specLogo/Holosmith.png';
export { default as SpellBreakerLogo } from './specLogo/Spellbreaker.png';
export { default as WeaverLogo } from './specLogo/Weaver.png';
export { default as MirageLogo } from './specLogo/Mirage.png';
export { default as DeadeyeLogo } from './specLogo/Deadeye.png';
export { default as FBLogo } from './specLogo/FireBrand.png';
export { default as SLBLogo } from './specLogo/Soulbeast.png';
export { default as ScourgeLogo } from './specLogo/Scourge.png';
export { default as RenegadeLogo } from './specLogo/Renegade.png';
export { default as ScrapperLogo } from './specLogo/Scrapper.png';
export { default as BladeswornLogo } from './specLogo/BladeSworn.png';
export { default as CatalystLogo } from './specLogo/Catalyst.png';
export { default as VirtuosoLogo } from './specLogo/Virtuoso.png';
export { default as SpecterLogo } from './specLogo/Specter.png';
export { default as WillBenderLogo } from './specLogo/Willbender.png';
export { default as UntamedLogo } from './specLogo/Untamed.png';
export { default as HarbingerLogo } from './specLogo/Harbinger.png';
export { default as VindiLogo } from './specLogo/Vindicator.png';
export { default as MechLogo } from './specLogo/Mechanist.png';

// Boss List
export { default as noBoss } from './bosses/noboss.png';
export { default as Wing1 } from './bosses/W1.png';
export { default as ValeGuardian } from './bosses/w1-vg.png';
export { default as Gorseval } from './bosses/w1-gorseval.png';
export { default as Sabetha } from './bosses/w1-sabetha.png';
export { default as Wing2 } from './bosses/W2.png';
export { default as Sloth } from './bosses/w2-sloth.png';
export { default as Mathias } from './bosses/w2-matthias.png';
export { default as Wing3 } from './bosses/W3.png';
export { default as Escort } from './bosses/w3-escort.png';
export { default as KC } from './bosses/w3-KC.png';
export { default as TwistedCastle } from './bosses/w3-tc.png';
export { default as Xera } from './bosses/w3-xera.png';
export { default as Wing4 } from './bosses/W4.png';
export { default as CairnMO } from './bosses/W4-cairn-mo.png';
export { default as Samarog } from './bosses/W4-samarog.png';
export { default as Deimos } from './bosses/W4-deimos.png';
export { default as Wing5 } from './bosses/W5.png';
export { default as SH } from './bosses/W5-desmina.png';
export { default as Dhuum } from './bosses/W5-dhuum.png';
export { default as Wing6 } from './bosses/W6.png';
export { default as CA } from './bosses/W6-Ca.png';
export { default as TwinLargos } from './bosses/W6-largos.png';
export { default as Qadim } from './bosses/W6-qadim.png';
export { default as Wing7 } from './bosses/W7.png';
export { default as Adina } from './bosses/W7-Adina.png';
export { default as Sabir } from './bosses/W7-Sabir.png';
export { default as QTP } from './bosses/W7-QadimP.png';